fix breaking change in set-required
use distributive conditional to expand union types as alternative fix for
https://github.com/sindresorhus/type-fest/commit/9c124971270e1476236af02505b774b5a1521127

- but alleviating chance of producing TS error TS2589: 'Type instantiation is excessively deep and possibly infinite'